### ISSUE TITLE
Uncaught TypeError: move is not a function

### ISSUE THREAD

**Issue by donakhseputa** [SupernovaIC/scrollable-tabs-bootstrat-5#2]
![image](https://user-images.githubusercontent.com/13846150/168048707-88670885-35e0-4f55-9c5d-ca4b987c89b3.png)

I have place `move.js` before `scrollable-tabs.min.js` on body tag

![image](https://user-images.githubusercontent.com/13846150/168049529-ca67a966-c88d-4d39-830a-d510ad411d97.png)

**Comment by FANMixco** [comment]
Thanks, @donny26utama, but this is the suggested code:

![image](https://user-images.githubusercontent.com/1666156/168059501-0cf93809-ac11-42a9-8ca9-1a8a5a3dc4ae.png)
